  checkout[m
  chore/graphify-knowledge-graph[m
* [32mdevelop[m
  feat/gemini-multimodal-rag[m
  feat/twelvelabs-pegasus-indexing[m
  feature/reapply-windows-changes[m
  fix/agent-stock-music-ai-workflows[m
  harkit/default-right-assistant-view[m
  harkit/hyperframes-motion-graphics[m
  harkit/index-enhance-tag-scene-descp-fix[m
  harkit/init-openshot-tutorial-hidden[m
  harkit/major-refactor-and-token-monitor[m
  harkit/new-video-tagging-and-indexing[m
  harkit/opeshot-assets-update[m
  harkit/perference-window-menu-item-color[m
  harkit/planning-agent-mode[m
  harkit/tagging-and-indexing[m
  harkit/video-timestamp-seraching-and-slicing-fixed[m
  harkit/video-transition-gen-and-morph-obj-replacement[m
  jashan/chat-markdown-rendering[m
  nilay-captioning-basic[m
  releases[m
  yc[m
  yc-harkit[m
