#!/usr/bin/env bash
# new-worktree.sh <feature> [--base <ref>]
# Creates $PORT_ROOT/<feature> on branch jashan/<feature> cut from the manifest base (origin/develop or the
# last unmerged dependency's branch), then bootstraps it: shared .venv symlink, .env copy, identity, .port-env.
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
FEATURE="${1:-}"; shift || true
[[ -n "$FEATURE" ]] || die "usage: new-worktree.sh <feature> [--base <ref>]"
require_feature "$FEATURE"
BASE_OVERRIDE=""
while [[ $# -gt 0 ]]; do case "$1" in --base) BASE_OVERRIDE="$2"; shift 2;; *) die "unknown arg $1";; esac; done
BRANCH="$BRANCH_PREFIX$FEATURE"
WT="$(wt_path "$FEATURE")"
cd "$PORT_MAIN_REPO"
log "fetching origin (and openshot if configured)"
git fetch -q origin --prune
git remote get-url openshot >/dev/null 2>&1 && git fetch -q openshot develop --tags || true
BASE="${BASE_OVERRIDE:-$(mf base "$FEATURE")}"
# A stacked base is a local branch name (jashan/<dep>); prefer origin's copy if it was pushed.
if [[ "$BASE" == jashan/* ]] && git show-ref -q --verify "refs/remotes/origin/$BASE"; then BASE_REF="origin/$BASE"; else BASE_REF="$BASE"; fi
git rev-parse -q --verify "$BASE_REF^{commit}" >/dev/null || die "base $BASE_REF does not exist (dependency worktree not created yet?)"
if [[ -d "$WT" ]]; then
  log "worktree already exists at $WT"
elif git show-ref -q --verify "refs/heads/$BRANCH"; then
  log "branch $BRANCH exists; attaching worktree"; git worktree add "$WT" "$BRANCH"
elif git show-ref -q --verify "refs/remotes/origin/$BRANCH"; then
  log "branch $BRANCH exists on origin; tracking it"; git worktree add --track -b "$BRANCH" "$WT" "origin/$BRANCH"
else
  log "creating $BRANCH from $BASE_REF"; git worktree add -b "$BRANCH" "$WT" "$BASE_REF"
fi
# ---- bootstrap ----
cd "$WT"
git config user.name "$GIT_NAME"; git config user.email "$GIT_EMAIL"
# branches cut before the tooling merged do not ignore these yet; info/exclude is shared by all worktrees
EXCL="$(git rev-parse --git-common-dir)/info/exclude"; touch "$EXCL"
for pat in .venv .port-env graphify-out/ .home/; do grep -qx "$pat" "$EXCL" || echo "$pat" >> "$EXCL"; done
[[ -e .venv ]] || ln -s "$PORT_MAIN_REPO/.venv" .venv
[[ -L .venv ]] || warn ".venv is not the shared symlink; two PyQt5 copies can crash libopenshot"
[[ -f .env || ! -f "$PORT_MAIN_REPO/.env" ]] || cp "$PORT_MAIN_REPO/.env" .env
[[ -f .claude/settings.json ]] || warn "branch predates the tooling; agent gets settings via --settings $PORT_SETTINGS"
DEPS_PREFIX="$(mf prefix "$FEATURE")"
PR_BASE="${BASE#origin/}"
cat > .port-env <<ENV
# generated by scripts/upstream-port/new-worktree.sh — sourced by launch-agent/run-app/test-all
export PORT_FEATURE="$FEATURE"
export PORT_ROOT="$PORT_ROOT"
export PORT_MAIN_REPO="$PORT_MAIN_REPO"
export PORT_SCRIPTS="$PORT_SCRIPTS"
export PORT_GUARD="$PORT_GUARD"
export PORT_SETTINGS="$PORT_SETTINGS"
export PORT_BRANCH="$BRANCH"
export PORT_BASE_BRANCH="$PR_BASE"
export PORT_BASE_REF="origin/develop"
export ZENVI_DEPS="$DEPS_PREFIX"
export ZENVI_OPENSHOT_INSTALL="$DEPS_PREFIX"
export PORT_LIBOPENSHOT_TAG="$(mf tag "$FEATURE")"
export PORT_LIBOPENSHOT_AUDIO_TAG="$(mf audio_tag "$FEATURE")"
ENV
PORT_FEATURE="$FEATURE" bash "$PORT_SCRIPTS/set-status.sh" bootstrapping --note "base $BASE"
python3 - "$STATE_DIR/$FEATURE.json" "$PR_BASE" "$WT" <<'PY'
import json,sys; p,base,wt=sys.argv[1:4]; d=json.load(open(p)); d["base"]=base; d["worktree"]=wt; json.dump(d,open(p,"w"),indent=2)
PY
log "worktree ready: $WT (branch $BRANCH, base $BASE, libopenshot $DEPS_PREFIX)"
