// Generated by Zenvi 9.9.9-test from the Zenvi project "Untitled".
// Re-exporting from Zenvi rewrites this file and src/zenvi/; add your own compositions in other files.
// Bring it back with File > Import Project > Remotion Project... in Zenvi.
import React from 'react';
import {Composition} from 'remotion';
import {z} from 'zod';
import {zColor} from '@remotion/zod-types';
import {ZenviTimeline, zenviTimeline} from './zenvi/ZenviTimeline';

export const zenviTimelineSchema = z.object({
  background: zColor(),
  volume: z.number().min(0).max(1),
  showTitles: z.boolean(),
});

export const RemotionRoot: React.FC = () => {
  const {width, height, fps, durationInFrames} = zenviTimeline.composition;
  return (
    <>
      <Composition
        id="ZenviTimeline"
        component={ZenviTimeline}
        durationInFrames={durationInFrames}
        fps={fps}
        width={width}
        height={height}
        schema={zenviTimelineSchema}
        defaultProps={{background: zenviTimeline.background, volume: 1, showTitles: true}}
      />
    </>
  );
};
