#!/usr/bin/env python3
"""Print the editor-capability coverage matrix as markdown.

Every capability from src/classes/editor_tools/coverage.py with the tool(s)
that serve it (editor tools via ``covers=``, older tools via LEGACY_COVERAGE),
grouped by workstream, then the capabilities left out on purpose with the
reason. Runs headless (no Qt, no libopenshot):

    python scripts/editor_tools_coverage_report.py > docs/agent-tools-coverage.md
"""

import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, os.path.join(ROOT, "tests"))
sys.path.insert(0, os.path.join(ROOT, "src"))


def main() -> int:
    import conftest  # noqa: F401  -- headless Qt/openshot stubs
    from classes import tool_handlers
    from classes.editor_tools import REGISTRY, coverage

    served = {}
    for spec in REGISTRY.values():
        for cid in spec.covers:
            served.setdefault(cid, []).append(spec.name)
    for cid, tools in coverage.LEGACY_COVERAGE.items():
        for t in tools:
            if t in tool_handlers.AGENT_TOOL_HANDLERS:
                served.setdefault(cid, []).append(t)

    total = len(coverage.CAPABILITIES)
    done = sum(1 for c in coverage.CAPABILITIES if c[0] in served)
    out = ["# Editor capabilities the Zenvi Assistant can use", "",
           f"Generated by `scripts/editor_tools_coverage_report.py`. {done} of {total} capabilities are "
           f"served by a tool; {len(coverage.OUT_OF_SCOPE)} are out of scope on purpose (listed at the end).",
           f"Editor tools registered: {len(REGISTRY)}; all agent tools: {len(tool_handlers.AGENT_TOOL_HANDLERS)}.", ""]
    by_ws = {}
    for cid, ws, where, what in coverage.CAPABILITIES:
        by_ws.setdefault(ws, []).append((cid, where, what))
    for ws in sorted(by_ws):
        out += [f"## {ws}", "", "| capability | where in the editor | tool(s) |", "|---|---|---|"]
        for cid, where, what in by_ws[ws]:
            tools = ", ".join(f"`{t}`" for t in sorted(set(served.get(cid, [])))) or "**missing**"
            out.append(f"| `{cid}` — {what} | {where} | {tools} |")
        out.append("")
    out += ["## Out of scope", "", "| capability | why |", "|---|---|"]
    for cid, reason in sorted(coverage.OUT_OF_SCOPE.items()):
        out.append(f"| `{cid}` | {reason} |")
    print("\n".join(out))
    return 0 if done == total else 1


if __name__ == "__main__":
    sys.exit(main())
